### ISSUE TITLE
Changing property in object does not trigger change

### ISSUE THREAD

**Issue by sKopheK** [sandiiarov/use-deep-compare#303]
Hi,
when I create new object with the same values, factory for `useDeepCompare*` is not executed, which is correct behavior. But when I update just a single property without object keeping the reference unchanged, no change is propagated even though component gets re-rendered. See demo for a pregntant example:

https://codepen.io/skophek/pen/bGPZGMJ

Not sure, if I get the usage right, but I'd assume any change should be examined.
If it's not the aim of this library, can you recommend me other that does deal with such use cases please?

**Comment by sandiiarov** [comment]
The malfunction you’re experiencing with `useDeepCompareMemo` isn’t due to an inherent flaw in the library but rather stems from improper state management practices in the `handleClick2` function.

In `handleClick2`, you’re directly mutating the state `o` by incrementing `s[0].mysound.count`. This is problematic for several reasons:

- Immutability Violation: React relies on immutability to efficiently determine when components need to re-render. By directly modifying the state, you bypass React’s change detection mechanisms.
- Potential Side Effects: Mutating state directly can lead to unpredictable side effects, making the component’s behavior harder to trace and debug.

React’s state management is built around the principle of immutability. When you update the state by creating a new object or array, React can efficiently determine that a change has occurred by comparing the previous and current state references. This enables optimized rendering and predictable component behavior.

However, when you mutate the state directly:

- React Doesn’t Detect Changes Properly: Since the state reference doesn’t change, React may not realize that an update has occurred, leading to components not re-rendering when they should.
- Breaks Pure Component Optimization: React components can optimize rendering by assuming that props and state are immutable. Direct mutations violate this assumption, potentially causing bugs and performance issues.

To resolve the problem, ensure that you’re updating the state immutably. Here’s how you can modify `handleClick2` to avoid direct mutation:

```typescript
const handleClick2 = () => {
  setO((prevO) => {
    // Create a deep copy of the state
    const newO = prevO.map(item => ({
      ...item,
      mysound: {
        ...item.mysound,
        count: item.mysound.count + 1
      }
    }));
    return newO;
  });
};
``` 

- Creating a New Object: Instead of modifying `s[0].mysound.count` directly, we create a new object that replicates the structure of the previous state but with the updated count.
- Ensuring Reference Changes: By returning a new array and new objects within it, React can accurately detect that the state has changed, ensuring that all related hooks like useDeepCompareMemo function as expected.

**Comment by sKopheK** [comment]
welcome to the world of [react-hook-form](https://react-hook-form.com) :)
